apiVersion: v1
kind: {{ .Values.mysql.volume.kind }}
metadata:
  name: {{ .Values.mysql.volume.name }}
  labels:
    type: local
spec:
  storageClassName: {{ .Values.mysql.volume.pvc.storageClass }}
  capacity:
    storage: {{ .Values.mysql.volume.pvc.storage }}
  accessModes:
    - {{ .Values.mysql.volume.pvc.accessMode }}
  hostPath:
    path: {{ .Values.mysql.volume.hostPath }}