apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.name }}
  labels: 
    group: {{ .Values.mysql.group }}
spec:
  clusterIP: {{ .Values.mysql.service.clusterIP }}
  selector:             
    app: {{ .Values.mysql.name }}
  ports:
    - port: {{ .Values.mysql.service.port }}        